### ISSUE TITLE
Invisible food

### ISSUE THREAD

**Issue by hunnib** [GopherMods/7DTDMods#1]
Modded food is invisible.  Can't see icons.  Can't see the required ingredients in either the description or in the campfire.  Can only see how many items I have.

**Comment by hunnib** [comment]
Please respond soon otherwise we will have to go elsewhere for our new yummy treats and you don't want that now do ya?

**Comment by GopherMods** [comment]
Hi hunnib!
Not sure why the food icons are invisible, but is there a UIAtlases folder inside the mod's folder?

**Comment by hunnib** [comment]
I already got rid of the file. I was busy with farmlife mods making my life hell. I will get your mod again later and look at it again. I am just hoping it jives with farmlife 3 expanded mod.  I will let you know. Thank for getting back to me. 

    On Thursday, September 24, 2020, 1:18:28 PM PDT, GopherMods <notifications@github.com> wrote:  
 
 


Hi hunnib!
Not sure why the food icons are invisible, but is there a UIAtlases folder inside the mod's folder?
